### ISSUE TITLE
Fix to issue with consuming data bytes

### ISSUE THREAD

**Issue by cmbaxter** [cppexpert/akka_flow_freezing#2]
Are you still looking for a help with this?  I see that you are consuming the response entity now, so the pool wedging issue is gone.  

BTW, sorry for taking an issue out.  Couldn't think of another way to reach you outside of Stackoverflow

**Comment by cppexpert** [comment]
Yes, I'm stuck and for now switched back to Apache HttpClient :(

**Comment by cmbaxter** [comment]
Okay, what about the code, in it's current form, do you want me to take a look at?

**Comment by cppexpert** [comment]
Yes, please.

**Comment by cmbaxter** [comment]
Okay, I created a PR.  The code was failing before my change due to a promise trying to be completed multiple times.  This stemmed from you explicitly consuming the data bytes first (to unblock the pool) and then the unmarshalling code trying to read it again.  I fixed this by reading the entity and then setting a strict entity back on the response to be read by the unmarshalling code

**Comment by cppexpert** [comment]
Thank you! What's the implication of making entity strict in terms of behavior and memory consumption ? And in what scenario 5 seconds might be not enough ?

**Comment by cmbaxter** [comment]
Ya, this will read everything into memory, so if you need to deal with large responses, you will have to rethink things.  But your Jsoup parsing is already expecting a fully formed (not lazy) Array[Byte] anyway.  If you need incremental parsing of responses, as the data becomes available in memory, then you will have to rethink things a little.

When you have a Chunked response, then toStrict will start the process of reading in the response chunks.  If for some reason the sending server is slow in getting the response chunk parts back to the client then it's possible you will hit that timeout.  

When I use toStrinct, I generally allow the requestor to provide an overall timeout for the request.  When I get back the initial response, I gauge home much time I have left against the total timeout and use the rest of that time when calling toStrict.

**Comment by ktoso** [comment]
As mentioned by @cmbaxter if your unmarshalling actually needs a strict thing anyway, there's no way we can make it magically work in a streaming way.

// In the WIP branch on https://github.com/akka/akka/pull/18745 I'm developing a way to do this "somewhat", but under the assumption that the streamis composed of multiple `T`'s, and we simply parse "one `T` at a time".

> When I use toStrinct, I generally allow the requestor to provide an overall timeout for the request. When I get back the initial response, I gauge how much time I have left against the total timeout and use the rest of that time when calling toStrict.

Yeah, that's a good way of using it.

**Comment by cppexpert** [comment]
Thank you, everyone!!
